pipeline {
    agent { label 'agent-01' }

    environment {
        SERVICE_NAME = "product-service"
        CONTAINER_NAME = "product-service"
        IMAGE_NAME = "product-service-image"
        PORT = "8080"
    }

    stages {
        stage('Checkout Code Github') {
            steps {
                git branch: 'main', url: 'https://github.com/ngxquang/DM-07-Microservices-SpringBoot.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    docker build -t ${IMAGE_NAME} ./${SERVICE_NAME}
                    """
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    sh "docker stop ${CONTAINER_NAME} || true"
                    sh "docker rm ${CONTAINER_NAME} || true"

                    sh """
                    docker run -d --name ${CONTAINER_NAME} \
                    --network=microservices-network \
                    -p ${PORT}:8080 ${IMAGE_NAME}
                    """
                }
            }
        }
    }
}
